// Generated by CoffeeScript 1.7.1
(function() {
  var d, handle_item_click, input_to_text, text_to_input, to_array;

  d = document;

  to_array = function(sequential_thing) {
    return Array.prototype.slice.call(sequential_thing);
  };

  input_to_text = function(input) {
    var text;
    text = d.createTextNode(input.value);
    text.addEventListener('click', function(e) {
      return text_to_input(e.target);
    });
    input.parentNode.replaceChild(text, input);
    return void 0;
  };

  text_to_input = function(text) {
    var input;
    console.log('converting');
    input = d.createElement('input');
    text.parentNode.replaceChild(input, text);
    return void 0;
  };

  handle_item_click = function(event) {
    var fn, item;
    item = event.target;
    console.log(item);
    console.log(item.firstChild.nodeType);
    fn = item.firstChild.nodeType === Node.TEXT_NODE ? text_to_input : input_to_text;
    fn(item.firstChild);
    return void 0;
  };

  d.addEventListener('DOMContentLoaded', function() {
    var input, _i, _len, _ref, _results;
    _ref = to_array(d.getElementsByTagName('input'));
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      input = _ref[_i];
      _results.push(input.addEventListener('blur', function(e) {
        return input_to_text(e.target);
      }));
    }
    return _results;
  });

}).call(this);
