// Generated by CoffeeScript 1.7.1
(function() {
  var d, handle_input_click, kill_event, to_array;

  d = document;

  to_array = function(sequential_thing) {
    return Array.prototype.slice.call(sequential_thing);
  };

  kill_event = function(event) {
    event.preventDefault();
    return event.stopPropagation();
  };

  handle_input_click = function(event) {
    var input, label, label_id;
    input = event.target;
    label_id = input.id + '_label';
    label = d.getElementById(label_id);
    return label.style.textDecoration = input.checked ? 'line-through' : '';
  };

  d.addEventListener('DOMContentLoaded', function() {
    var input, label, _i, _j, _len, _len1, _ref, _ref1, _results;
    _ref = to_array(d.getElementsByTagName('label'));
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      label = _ref[_i];
      label.addEventListener('click', kill_event);
    }
    _ref1 = to_array(d.getElementsByTagName('input'));
    _results = [];
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      input = _ref1[_j];
      _results.push(input.addEventListener('click', handle_input_click));
    }
    return _results;
  });

}).call(this);
